apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: devsecops
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'kubernetes-pods'
      kubernetes_sd_configs:
      - role: pod
    rule_files:
    - "alerts.yml"
  alerts.yml: |
    groups:
    - name: k8s-alerts
      rules:
      - alert: HighPodRestarts
        expr: increase(kube_pod_container_status_restarts_total[5m]) > 3
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High pod restarts detected {{ $labels.pod }}"
      - alert: HighCPUUsage
        expr: sum(rate(container_cpu_usage_seconds_total[5m])) by (pod) > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.pod }}"
